# Generated by Django 5.1.7 on 2025-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('student_id', models.AutoField(db_column='student_ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=65)),
                ('lastname', models.CharField(db_column='Lastname', max_length=65)),
                ('course', models.CharField(db_column='Course', max_length=265)),
                ('year', models.IntegerField(db_column='Year')),
            ],
            options={
                'db_table': 'test_table',
                'managed': False,
            },
        ),
    ]
