# Generated by Django 5.1.6 on 2025-03-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTable',
            fields=[
                ('student_id', models.CharField(db_column='student_ID', max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=200)),
                ('lastname', models.CharField(db_column='Lastname', max_length=200)),
                ('course', models.CharField(db_column='Course', max_length=200)),
                ('module', models.CharField(db_column='Module', max_length=200)),
                ('student_photo', models.ImageField(db_column='Student_Photo', upload_to='attended_students_photos/')),
                ('Attendance', models.CharField(choices=[('Attended', 'Attended'), ('Late', 'Late'), ('Unattended', 'Unattended')], db_column='Attendance', max_length=20)),
                ('AttendanceDate', models.DateField(db_column='Attendance_Date')),
                ('AttendanceTime', models.TimeField(db_column='Attendance_Time')),
            ],
            options={
                'db_table': 'attendance table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_id', models.CharField(db_column='student_ID', max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=265)),
                ('lastname', models.CharField(db_column='Lastname', max_length=265)),
                ('course', models.CharField(db_column='Course', max_length=265)),
                ('year', models.IntegerField(db_column='Year')),
                ('phone_number', models.IntegerField(db_column='Phone_Number')),
                ('email', models.EmailField(db_column='E-mail', max_length=265)),
                ('id_photo', models.ImageField(db_column='ID_Photo', upload_to='studentsID_photos/')),
            ],
            options={
                'db_table': 'student_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('user_id', models.AutoField(db_column='user_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_details',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
