# Generated by Django 5.1.6 on 2025-04-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0002_classschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_ID', models.CharField(db_column='student_ID', max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=265)),
                ('lastname', models.CharField(db_column='Lastname', max_length=265)),
                ('course', models.CharField(db_column='Course', max_length=265)),
                ('year', models.IntegerField(db_column='Year', max_length=2)),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=13)),
                ('email', models.CharField(db_column='Email', max_length=265)),
                ('id_photo', models.ImageField(db_column='ID_Photo', upload_to='studentsID_photos/')),
            ],
            options={
                'db_table': 'student_details',
                'managed': False,
            },
        ),
    ]
