# Generated by Django 5.1.6 on 2025-04-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_system', '0003_studentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('staff_ID', models.IntegerField(db_column='staff_ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='Firstname', max_length=265)),
                ('lastname', models.CharField(db_column='Lastname', max_length=265)),
                ('lecture_course', models.CharField(db_column='Lecture_Course', max_length=265)),
                ('lecture_modules', models.CharField(db_column='Lectue_Modules', max_length=265)),
                ('personal_email', models.CharField(db_column='Personal_Email', max_length=265)),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=13)),
            ],
            options={
                'db_table': 'staff_details',
                'managed': False,
            },
        ),
    ]
